

api:
  secret: 0x000000000000000000000
  endpoint: http://fancymc.net/api/paper
  headers:
    Minecraft-Server: atlanta

# default use player name as index
# change to true if you want to use uuid index instead
storage-uuid-mode: false