name: ${project.name}
main: ${project.group}.FancyInboxStorage
version: ${project.version}
api-version: 1.18

author: Alexzvn
website: https://github.com/alexzvn
softdepend:
  - PlaceholderAPI
  - InteractiveChat
  - InteractiveChatDiscordSrvAddon